:asys:
    :bank:
        :normal_savings:
            :username: "asystest503"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Sateesh"
            :strongauth: true
        :normal_ira:
            :username: "asystest510"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Lamar"
            :strongauth: true
        :normal_checking:
            :username: "asystest508"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Jodi"
            :strongauth: true
        :zero_balance_savings:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :zero_balance_ira:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :zero_balance_checking:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
    :card:
        :cbb:
            :username: "6011000805765421"
            :password: "ccccc"
            :security_answer: "test"
            :name: "Ln553890976"
            :strongauth: false
        :miles:
            :username: "uidsm2830"
            :password: "solstice123"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :send_money:
            :username: "6011000015856580"
            :password: "solstice123"
            :security_answer: "test"
            :name: "Ln374691273"
            :strongauth: false
        :extras:
            :username: "6011000978752131"
            :password: "ccccc"
            :security_answer: "test"
            :name: "Ln448644812"
            :strongauth: false
    :sso:
        :normal:
            :username: "asysssocred4"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Ln227052855"
            :strongauth: true
:mst0:
    :bank:
        :normal_savings:
            :username: "mstotrn204"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Edna"
            :strongauth: true
        :normal_ira:
            :username: "mstotrn203"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Melody"
            :strongauth: true
        :normal_checking:
            :username: "mstotrn112"
            :password: "pass123$"
            :security_answer: "test"
            :name: "Vickie"
            :strongauth: true
        :zero_balanace_savings:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :zero_balance_ira:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :zero_balance_checking:
            :username: "TODO"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
    :card:
        :cbb:
            :username: "000000795017"
            :password: "ccccc"
            :security_answer: "test"
            :name: "Keh-Cherng"
            :strongauth: true
        :miles:
            :username: "208901214612"
            :password: "ccccc"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true
        :send_money:
            :username: "000017430103"
            :password: "ccccc"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: false
        :extras:
            :username: "000017430103"
            :password: "ccccc"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: false
    :sso:
        :normal:
            :username: "mst0sso105"
            :password: "pass123$"
            :security_answer: "test"
            :name: "TODO"
            :strongauth: true

:loading_label: "In progress"
:afternoon_hour: 12
:evening_hour: 18